services:
  - type: web
    name: hoymismogps-frontend
    runtime: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    envVars:
      - key: NODE_VERSION
        value: 20.11.0
      - key: VITE_API_BASE_URL
        value: https://hoymismogps-backend.onrender.com
      - key: VITE_FIREBASE_API_KEY
        value: AIzaSyDJBIASAEKY6nZRYC2OekMQwtNIn4sW108
      - key: VITE_FIREBASE_AUTH_DOMAIN
        value: hoymismogps.firebaseapp.com
      - key: VITE_FIREBASE_DATABASE_URL
        value: https://hoymismogps-default-rtdb.firebaseio.com
      - key: VITE_FIREBASE_PROJECT_ID
        value: hoymismogps
      - key: VITE_FIREBASE_STORAGE_BUCKET
        value: hoymismogps.firebasestorage.app
      - key: VITE_FIREBASE_MESSAGING_SENDER_ID
        value: 1098450733119
      - key: VITE_FIREBASE_APP_ID
        value: 1:1098450733119:web:3783fc00cf271ee7d5508a
    routes:
      - type: rewrite
        source: /*
        destination: /index.html